name: 'sv_dbt_examples'
version: '1.0.0'
config-version: 2
profile: 'default'

models:
  my_new_project:
    +materialized: table
    source_prepared:
      app:
    
      
snapshots:
  sources:
    app:
      - name: snapshot_source_app_users

seeds:
  sv_dbt_examples:  
    app:
      prepared_app_users:
        +column_types:
          user_id: bigint
          first_name: varchar(255)
          src_created_at: timestamptz
          src_updated_at: timestamptz
          dw_created_at: timestamptz
          dw_updated_at: timestamptz



model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
