name: 'sv_dbt_examples'
version: '1.0.0'
config-version: 2
profile: 'default'

models:
  sv_dbt_examples:
    #+database: sv_dbt_examples
    #+schema: dbt_astanton 
    +materialized: table
    source_prepared:
      app:
    
      
snapshots:
  #+target_database: "sv_dbt_examples"
  +target_schema: "dbt_astanton"
  +invalidate_hard_deletes: true
  sources:
    app:
      - name: snapshot_source_app_users

seeds:
  #+database: sv_dbt_examples
  #+schema: dbt_astanton
  sv_dbt_examples:  
    app:
      seed_prepared_app_users:
        +column_types:
          user_id: bigint
          first_name: varchar(255)
          src_created_at: timestamptz
          src_updated_at: timestamptz
          dw_created_at: timestamptz
          dw_updated_at: timestamptz
      seed_prepared_app_users_with_previous:
        +column_types:
          user_id: bigint
          first_name: varchar(255)
          src_created_at: timestamptz
          src_updated_at: timestamptz
          dw_created_at: timestamptz
          dw_updated_at: timestamptz
      users:
        +identifier: users
        +column_types:
          id: bigint
          first_name: varchar(255)
          created_at: timestamptz
          updated_at: timestamptz 



model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
